drop table if exists event_compilation cascade;
drop table if exists compilations cascade;
drop table if exists comments cascade;
drop table if exists events cascade;
drop table if exists participation cascade;
drop table if exists categories cascade;
drop table if exists users cascade;


create table if not exists users
(
    id    bigint generated by default as identity not null,
    email varchar(300),
    name  varchar(300),
    constraint pk_user primary key (id),
    constraint uq_email unique (email),
    constraint uq_name unique (name)

);

create table if not exists categories
(
    id   bigint generated by default as identity not null,
    name varchar(60),
    constraint pk_category primary key (id),
    constraint unique_name unique (name)
);

create table if not exists events
(
    id                 bigint generated by default as identity not null,
    annotation         varchar(2200),
    category_id        bigint references categories (id),
    creation_on        timestamp without time zone,
    description        varchar(7200),
    event_date         timestamp without time zone,
    initiator_id       bigint references users (id),
    paid               boolean,
    participant_limit  bigint,
    published_on       timestamp without time zone,
    request_moderation boolean,
    state              varchar(15),
    title              varchar(150),
    views              bigint,
    longitude          real,
    latitude           real,
    constraint pk_event primary key (id),
    constraint zero_limit check ( participant_limit >= 0 )
);

create table if not exists participation
(
    id           bigint generated by default as identity not null,
    created      timestamp without time zone,
    event_id     bigint references events (id),
    requester_id bigint references users (id),
    status       varchar(15),
    constraint pk_participation primary key (id)
);

create table if not exists compilations
(
    id     bigint generated by default as identity not null,
    pinned boolean,
    title  varchar(150),
    constraint pk_compilation primary key (id)
);

create table if not exists event_compilation
(
    event_compilation_id bigint generated by default as identity not null,
    event_id             bigint references events (id),
    compilation_id       bigint references compilations (id),
    constraint pk_compilation_event primary key (event_compilation_id),
    foreign key (event_id) references events (id) on delete cascade,
    foreign key (compilation_id) references compilations (id) on delete set null

);

create table if not exists comments
(
    id bigint generated by default as identity not null,
    event_id   bigint references events (id),
    user_id    bigint references users (id),
    comment    varchar(5100)                           not null,
    comment_date timestamp without time zone not null,
    constraint pk_comment_id primary key (id),
    foreign key (event_id) references events (id) on delete cascade,
    foreign key (user_id) references users on delete set null

)
