drop table if exists endpoint_hit;

create table if not exists endpoint_hit
(
  id bigint generated by default as identity not null,
  app varchar (50),
  uri varchar (50),
  ip varchar(50),
  timestamp timestamp without time zone,
  constraint id_endpoint primary key (id)
);


